#!/bin/bash

## Techfile:
./preproc.py sky130.tech sky130.tech.new\
 -DTECHNAME=sky130\
 -DREVISION=9.9999hilas\
 -DMETAL5\
 -DMIM\
 -DREDISTRIBUTION

mv sky130.tech.new sky130.tech



# remove triple commented lines:
sed -i \
'/###.*'\
'/d' *.magicrc


# DO NOT SET PDKPATH:
sed -i 's'\
'/Allow override of PDK path from environment variable PDKPATH'\
'/REQUIRE PDK path from environment variable PDKPATH'\
'/g' *.magicrc

sed -i 's'\
'/^\s*set PDKPATH "STAGING_PATH\/TECHNAME"'\
'/    puts "this script requires environment variable PDKPATH to be set"\n    exit 1'\
'/g' *.magicrc

## Load Techfie:
sed -i 's'\
'/# loading technology'\
'/# loading technology\n'\
'tech load \$PDKPATH\/libs.tech\/magic\/TECHNAME.tech'\
'/g' *.magicrc

# remove the '#ifdef FULLTECH' section:
sed -i 's/# add path to GDS cells//g' *.magicrc

sed -i \
'/#ifdef FULLTECH/'\
',/#endif'\
'/d' *.magicrc

# MAGIC library section:
sed -i 's'\
'/addpath ${PDKPATH}\/libs.ref\/${MAGTYPE}\/sky130_sram_macros'\
'/addpath ${PDKPATH}\/libs.ref\/${MAGTYPE}\/sky130_sram_macros\n'\
'    addpath ${PDKPATH}\/libs.ref\/${MAGTYPE}\/sky130_hilas_sc'\
'/g' \
*.magicrc

sed -i 's'\
'/addpath ${PDKPATH}\/libs.ref\/sky130_sram_macros\/${MAGTYPE}'\
'/addpath ${PDKPATH}\/libs.ref\/sky130_sram_macros\/${MAGTYPE}\n'\
'    addpath ${PDKPATH}\/libs.ref\/sky130_hilas_sc\/${MAGTYPE}'\
'/g' \
*.magicrc


#  GDS Section
sed -i 's'\
'/addpath ${PDKPATH}\/libs.ref\/gds\/sky130_sram_macros'\
'/addpath ${PDKPATH}\/libs.ref\/gds\/sky130_sram_macros\n'\
'    addpath ${PDKPATH}\/libs.ref\/gds\/sky130_hilas_sc'\
'/g' \
*.magicrc

sed -i 's'\
'/addpath ${PDKPATH}\/libs.ref\/sky130_sram_macros\/gds'\
'/addpath ${PDKPATH}\/libs.ref\/sky130_sram_macros\/gds\n'\
'    addpath ${PDKPATH}\/libs.ref\/sky130_hilas_sc\/gds'\
'/g' \
*.magicrc

# replace MAGIC_CURRENT
sed -i 's'\
'/MAGIC_CURRENT'\
'/libs.tech\/magic'\
'/g' \
*.magicrc

# replace TECHNAME
sed -i 's'\
'/TECHNAME'\
'/sky130'\
'/g' *.magicrc

## set techfile version:
#sed -i 's'\
#'/REVISION'\
#'/9.9.9.9hilas'\
#'/g' \
#*.tech

