#! /usr/bin/env bash
#! /usr/bin/env bash

mk_input(){
    INPUT=''
    for f in "${@}"; do
        INPUT="${INPUT}"$'\r\n'"load ${f} -force"$'\r\n'"lef write -tech"
    done
}

do_it(){
magic -dnull -noconsole -rcfile sky130A.magicrc << EOF
$INPUT
quit -noprompt
EOF
}

mk_input "${@}"
echo "${INPUT}"
do_it
for f in "${@}";do
  mv "${f%.*}.lef" ../lef/
done
