#! /usr/bin/env bash

mk_input(){
    INPUT=''
    for f in "${@}"; do
        INPUT="${INPUT}"$'\r\n'"load ${f} -force"$'\r\n'"gds merge"$'\r\n'"gds write ${f%.*}.gds"
    done
}

do_it(){
magic -dnull -noconsole -rcfile sky130A.magicrc << EOF
$INPUT
quit -noprompt
EOF
}

mk_input "${@}"
echo "${INPUT}"
do_it
test -d ../gds || mkdir ../gds
for f in "${@}";do
  mv "${f%.*}.gds" ../gds/
done
