#! /usr/bin/env bash

# first argument is path to magic files
# second arg.    is path to write GDS output

targ_dir=${2}
src_dir=${1}

mk_input(){
    INPUT=''
    for f in $(find "${src_dir}" -iname "*.mag"); do
        tfile=$(basename ${f})
        INPUT="${INPUT}"$'\r\n'"load ${f} -force"$'\r\n'"gds merge"$'\r\n'"gds write"
    done
}

do_it(){
magic -dnull -noconsole -rcfile "${MAGICRC}" << EOF
"${INPUT}"
quit -noprompt
EOF
}

#echo "using rcfile: ${MAGICRC}"
mk_input
#echo "${INPUT}"
cd ${targ_dir}
do_it
