#! /usr/bin/env bash

# first argument is path to magic files
# second arg.    is path to write LEF output

src_dir="${1}"
targ_dir="${2}"

do_it(){
magic -dnull -noconsole -rcfile "${MAGICRC}" -T "${TECHFILE}" << EOF
load "${1}" -force
lef write -tech -hide
quit -noprompt
EOF
}

cd "${targ_dir}"
set -e
for f in $(find "${src_dir}" -iname "*.mag"); do
  echo
  echo
  echo "#######################################################################"
  echo "#   Generating LEF from: $(basename "${f}") "
  echo "#######################################################################"
  do_it "${f}"
done
