#! /usr/bin/env bash

# first argument is path to magic files
# second arg.    is path to write GDS output

targ_dir="${2}"
src_dir="${1}"

do_it(){
  magic -dnull -noconsole -rcfile "${MAGICRC}" -T "${TECHFILE}" << EOF
drc off
load "${1}" -force
drc off
gds readonly true
gds rescale false
gds merge
gds flatten
gds write "${targ}"
quit -noprompt
EOF
}

cd ${targ_dir}
set -e
for f in $(find "${src_dir}" -iname "*.mag"); do
  targ=$(basename ${f})
  targ="${targ%.*}".gds
  echo
  echo
  echo "######################################################################"
  echo "#   Making GDS from: $(basename "${f}") "
  echo "#   Will write to: ${targ} "
  echo "######################################################################"
  do_it "${f}"
done
